---
language: python
env:
  global:
  - secure: "" # AWS_ACCESS_KEY_ID=xyz
  - secure: "" # AWS_SECRET_ACCESS_KEY=xyz
  - 'AWS_DEFAULT_REGION=us-east-1'
python:
- '2.7'
install:
- 'pip install yamllint'
- 'pip install awscli'
script:
- 'yamllint .'
- 'find . -type f \( -name ''*.yml'' -o -name ''*.yaml'' \) -a ! -name ''.*'' | while read file; do set -ex && grep -q "LICENSE-2.0" "$file"; done;'
- 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then find . -type f \( -name ''*.yml'' -o -name ''*.yaml'' \) -a ! -name ''.*'' | while read file; do set -ex && aws cloudformation validate-template --template-file "file://$file" > /dev/null; done; fi'
